# Generated by Django 4.1.6 on 2023-02-12 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AlbumSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_number', models.IntegerField()),
                ('album_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.album')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('album_songs', models.ManyToManyField(to='API.albumsong')),
            ],
        ),
        migrations.AddField(
            model_name='albumsong',
            name='song_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.song'),
        ),
        migrations.AddField(
            model_name='album',
            name='album_songs',
            field=models.ManyToManyField(to='API.albumsong'),
        ),
        migrations.AddField(
            model_name='album',
            name='artist_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.artist'),
        ),
        migrations.AddConstraint(
            model_name='albumsong',
            constraint=models.UniqueConstraint(fields=('album_obj', 'song_obj'), name='Unique together album and song constraint', violation_error_message='album and song must be unique together'),
        ),
        migrations.AddConstraint(
            model_name='albumsong',
            constraint=models.UniqueConstraint(fields=('album_obj', 'song_number'), name='Unique together album and song_number constraint', violation_error_message='album and song_number must be unique together'),
        ),
        migrations.AddConstraint(
            model_name='albumsong',
            constraint=models.UniqueConstraint(fields=('song_number', 'song_obj'), name='Unique together song_number and song constraint', violation_error_message='song_number and song must be unique together'),
        ),
    ]
